### ISSUE TITLE
Make touched_crates() detection more robust

### ISSUE THREAD

**Issue by Veetaha** [elastio/devx#37]
The current heuristic to infer the crates for rust files is that we search for `src/` component in the changed file path and look for a `Cargo.toml` file at that path. This works in 80% of the cases, but it fails when the files reside under some other dir, for example `tests/`.
We should fix this and just do a search for `Cargo.toml` file in all parent directories of the changed files.

https://github.com/elastio/devx/blob/cd8d3f730bef8e4074653093e1ca642b3a46540e/devx-pre-commit/src/lib.rs#L143-L161

**Comment by anelson** [comment]
You might find `cargo metadata` interesting.  It produces JSON output which can be manipulated programmatically.  I think there's a crate with Rust types one can deserialize the metadata into.  This would let you use Cargo's own implementation to determine what directories correspond to what crates.

**Comment by Veetaha** [comment]
I'd like to avoid using `cargo metadata` for now because it's a big dependency and also take up to a second to run
